### ISSUE TITLE
What rate scheme / data source is returned for historic data?

### ISSUE THREAD

**Issue by alerque** [VoirDev/exchangeit#2]
I've arrived here looking for an alternative to the new defunct exchangerate.host. I was able to setup queries for my use case (personal financing) without too much trouble. Thank you for that.

For me use case I keep a cache of historic values of all days that I have transactions for in all currencies that I hold (as a traveler and expat it's a few). This means I only need to query an API for rates once for each day in my history.

However using a new API I've been going back and updating my historical data. The exchangerate.host API occasionally returned bogus data on some days and I didn't always catch it, so I'm interested in flushing out my cache and rebuilding it. To that end I've been doing some spot checks on old data and am trying to figure out what rates are actually being returned.

For example lets use a base rate of USD and look into TRY values for June 30th, 2022. Here are the old and new values from my cached price ledger data:

```patch
-P 2022-06-30 USD 16.683295842790236918062874 TRY
+P 2022-06-30 USD 16.679515 TRY
```

I can understand the significant digits and rounding are going to be different, but this is also just different by ₺0.004. For the same day [XE returns 16.707547096582005](https://www.xe.com/currencytables/?from=TRY&date=2022-06-30#table-section) and claims it as the mid-market rate, which is even more different than the exchangerate.host vs exchangeit.app difference! Other popular sites more closely match the XE value, e.g. [x-rates has 16.707547](https://www.x-rates.com/historical/?from=TRY&amount=1&date=2022-06-30) as well.

What is the data source here and does anybody know what explains these differences?

**Comment by CheckSanity** [comment]
Hello there,

Exchange It API uses multiple data sources for each currency and date.
For example, for June 30th, 2022 API has data from 3 different sources. Each source has different priority and API takes rate with the highest one.

Exchange It API doesn't use any paid solutions on the market and parses and stores data from free sources and APIs.
For example, currently received value `2022-06-30 USD -> TRY = 16.679515`  is taken from legacy exchangerate.host API

Disclosure of synchronization sources is planned in the [roadmap](https://github.com/VoirDev/exchangeit#roadmap) and in the future the user will be able to choose which of the sources he would like to use

Along with this, I am integrating new data sources, including for historical rates, so that in the future the value can be adjusted as new sources with more accurate data appear.

If you want to recommend a free data source, please create new issue with a detailed description of the provider and I will add it to the synchronization if its possible

I hope I was able to help you, thank you for your question.
Please feel free to share your comments and ideas

**Comment by alerque** [comment]
Thanks. In other words the data set is a hodge-podge and there is no way of knowing what the source even is and it might be polluted with the same bogus data I was trying to clean out from my own earier exchangerate.host usage. I other words I should be using everything as a loose guesstimate eh? I guess I should eventually look into more official / auditable data sources. Still thanks for the info.

By the way are you sure "taking the highest value" makes sense? What if one of your data sets is representing a *minimum*/*maximum* value for the day instead of the average mid-market rate? Won't that skew the whole data set?

**Comment by CheckSanity** [comment]
At the current stage of the project, you are probably right, you should not treat rates as the absolute truth and if you need more stable rates, then you should consider paid services

The thing is that it is very difficult to find official "banking" data in the public domain, and this data may differ from the data that trading exchanges show, but I'm working on it :)

Currently, each data source has an internal priority, and we take not the highest rate value, but with highest priority. For example, for same date we have usd -> try from source with priority 10, and from source with priority 30. Since API not supports selecting data source (for now), you will receive rate value with priority 30
The more stable data source, the higher priority it has. For example, central europe bank data has priority 80.

I am currently developing micro-service that will allow receive data from an open source that contains minimum maximum values, as well as values at the beginning and end of trading day. As soon as this data starts appearing in the database, I can return it from the API

**Comment by alerque** [comment]
> Currently, each data source has an internal priority, and we take not the highest rate value, but with highest priority. For example, for same date we have usd -> try from source with priority 10, and from source with priority 30. Since API not supports selecting data source (for now), you will receive rate value with priority 30
> The more stable data source, the higher priority it has. For example, central europe bank data has priority 80.

Thanks, I misunderstood your earlier note. Ranking the stability of a sources is much better than taking whichever value is higher in the data!

And yes I know finding public domain data sets that are any good is a hard problem. I appreciate that you're trying.

It would probably be useful to return some info about what the data represents: for example the biggest difference I think I'm seeing is the difference between data that is average mid-market vs. data that is close-of-market value.
