### ISSUE TITLE
Gold (XAU) data prior to 2020-05-02 missing

### ISSUE THREAD

**Issue by alerque** [VoirDev/exchangeit#3]
May 2nd, 2020 appears to be the earliest data available for Gold (XAU). This seems a bit of out step with other exchange data that goes back much farther. It's not like gold is a particular newcomer to the financial scene ;-)

**Comment by CheckSanity** [comment]
I just checked couple responses for [2020-05-01](https://api.exchangeit.app/currencies/xau/daily?date=2020-05-01), [2012-02-01](https://api.exchangeit.app/currencies/xau/daily?date=2012-02-01) and it seems it returns some data.

Can you please provide request you made?

**Comment by alerque** [comment]
My queries were failing for most queries in 2006-2020, and with some trial and error I narrowed it down to that date:

```console 
$ curl -s 'https://api.exchangeit.app/currencies/USD/daily?date=2020-05-01&codes[]=XAU' | jq
{
  "copyright": {
    "title": "Thank you for choosing Exchange It API",
    "description": "We're excited to see the incredible things you'll achieve with it. If you have any questions or need support, our team is here to help.",
    "url": "https://exchangeit.app",
    "email": "hello@exchangeit.app"
  },
  "data": {
    "code": "usd",
    "title": "United States Dollar",
    "date": "2020-05-01",
    "rates": []
  }
}
$ curl -s 'https://api.exchangeit.app/currencies/USD/daily?date=2020-05-02&codes[]=XAU' | jq
{
  "copyright": {
    "title": "Thank you for choosing Exchange It API",
    "description": "We're excited to see the incredible things you'll achieve with it. If you have any questions or need support, our team is here to help.",
    "url": "https://exchangeit.app",
    "email": "hello@exchangeit.app"
  },
  "data": {
    "code": "usd",
    "title": "United States Dollar",
    "date": "2020-05-02",
    "rates": [
      {
        "code": "xau",
        "rate": 0.000588
      }
    ]
  }
}
```

**Comment by CheckSanity** [comment]
I see, it seems that currently USD has no direct exchange rate for XAU. However, XAU has direct exchange rate for USD.
Since the reverse exchange rate only theoretical value it is not good to provided it as source of truth.

Actually, this may be a good fallback in separate optional field with `reverseRate` name, so you can get a fallback if needed.
Would put it in my TODO list, thanks!

**Comment by alerque** [comment]
I don't understand what you mean by "direct". Again similar to my question #2, what rate is being represented here? If these are mid-market rates then then there should be no such thing as "direct" vs. "reverse" or "only theoretical". It's just a divide by 1 equation and if you know one value you can figure out the other. In other words whichever way you data source has the exchange you can return the inverse for the base currency being the other direction. Spot checking some other currencies on various dates that do return values each way (for example TRY→USD and USD→TRY) they do appear to be mathematical inverses, so these are **not** some banks buy and sell rates stored separately. I don't see why the API shouldn't return a values computed from the inverse if all that is being represented is mid-market.

**Comment by CheckSanity** [comment]
Okay, let's imagine that we have source 1 - the central bank of Europe and there is source 2 - for example, the central bank of Turkey

the central bank operates only with its own currency and it turns out that it provides a direct rate and on its basis we can calculate the reverse one, which will be applicable only to the same bank

So, if according to the central European bank 1 euro is, for example, 30 liras and it turns out that one lira is 0.03 euros
and in this case it only applies to the rate of the specific one bank

But this does not mean at all that according to the central Turkish bank the inverse value obtained for the lira will be correct, because it may report that, for example, one lira is 0.04 euros

it turns out that if we want to get the exact exchange rate values for the euro, then we should get the values from the official resource of the bank issuing the currency. For the lira, the only source of truth will be the central Turkish bank

I think there is such confusion for you because at the moment, you cannot manually select one specific data source and the values are selected based on the most suitable
it is for this reason that euro to lira is not equal to the inverse value of lira to euro, since their direct rates can be obtained from different sources

if you could specify the source from which you want to receive rates, then the values would match and this won't be so confusing

**Comment by CheckSanity** [comment]
Check current rates for provided examples on 5th february:

Europe Central Bank - https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html

eur -> try = 32.8313

Turkey - https://www.tcmb.gov.tr/wps/wcm/connect/en/tcmb+en/main+menu/statistics/exchange+rates/indicative+exchange+rates

eur -> try = 32.8052 | 32.8643 | 32.7823 | 32.9136

**Comment by CheckSanity** [comment]
The API completely reworked and optimized, closing since the whole ticket is not valid anymore
